<div style="height:46px;background-image: url(image/agree.svg);background-repeat: repeat-x;margin-top:-46px;">
</div>

<div style="height:100px;background:#565656;color:#FFF;text-align:center;padding-top:10px;">
	<div style="padding-top:20px;">© 2016 Enlamiao, all rights reserved.</div>
</div>


<!--
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div style="height:46px;background-image: url(image/agree.svg);background-repeat: repeat-x;margin-top:-46px;">
			</div>
		</div>
	</div>
</div>
-->