<!-- logo start -->
 <div style="width:100%;background:#565656;height:120px;">
  <a href="/enlamiao">
    <div style="padding-top:20px;height:80px;line-height:80px;"><img src="image/logo01.svg" width="100%" height="80px"></div>
  </a>  
 </div>
<!-- logo end --> 
<div style="width: 100%;height: 55px;line-height:55px;border-top: 1px solid #d2d2d2;border-bottom: 1px solid #e5e5e5;background-color: #fafafa;">
		<marquee behavior="scroll" contenteditable="true" onstart="this.firstChild.innerHTML+=this.firstChild.innerHTML;" scrollamount="3" width="80%" onmouseover="this.stop();" onmouseout="this.start();"> 
		<img src="image/calendar.svg" width="15px"> 只需三步,建设高效执行力团队
		</marquee>

</div>