<!-- 
 <div style="width:100%;background:#565656;height:120px;">
  <a href="/enlamiao">
    <div style="padding-top:20px;height:80px;line-height:80px;"><img src="image/logo01.svg" width="100%" height="80px"></div>
  </a>  
 </div>

<div style="width: 100%;height: 55px;line-height:55px;border-top: 1px solid #d2d2d2;border-bottom: 1px solid #e5e5e5;background-color: #fafafa;">
		<marquee behavior="scroll" contenteditable="true" onstart="this.firstChild.innerHTML+=this.firstChild.innerHTML;" scrollamount="3" width="80%" onmouseover="this.stop();" onmouseout="this.start();"> 
		<img src="image/calendar.svg" width="15px"> 只需三步,建设高效执行力团队
		</marquee>

</div>
-->



<div style="background-color:#565656;width:100%;">
	<div class="container">
	  <div class="row">
	    <div class="col-md-4">
		    <div style="padding-top:10px;padding-bottom:10px;">
			    <a href="/">
			    	<img src="image/logo01.svg" width="100%">
		  		</a>
		  	</div>	
	    </div>
	  </div>
	</div>
</div> 

<div style="border-top: 1px solid #d2d2d2;border-bottom: 1px solid #d2d2d2;background-color: #e5e5e5;width:100%;">
	<div class="container">
	  <div class="row">
	  	<div class="col-md-12">
	  		<div style="width: 100%;height: 25px;line-height:25px;">
	  			<marquee behavior="scroll" contenteditable="true" onstart="this.firstChild.innerHTML+=this.firstChild.innerHTML;" scrollamount="3" width="80%" onmouseover="this.stop();" onmouseout="this.start();"><img src="image/calendar.svg" width="15px"> 只需三步,建设高效执行力团队
				</marquee>
	  		</div>
	  	</div>
	  </div>
	 </div>
</div>	 

	  
